In [36]:
import pandas as pd
import string
from typing import List

In [31]:
words = pd.read_csv('word-list.txt',header=None)
words = words.rename(columns={0:'word'})
words = words['word'].apply(lambda x: pd.Series(list(x)))

In [33]:
words['probs'] = 1

In [34]:
words

       0  1  2  3  4  probs
0      w  o  m  e  n      1
1      n  i  k  a  u      1
2      s  w  a  c  k      1
3      f  e  e  n  s      1
4      f  y  l  e  s      1
...   .. .. .. .. ..    ...
12942  m  o  t  o  r      1
12943  g  e  u  m  s      1
12944  g  r  i  t  s      1
12945  k  a  m  e  s      1
12946  d  e  a  t  h      1

[12947 rows x 6 columns]

In [39]:
letters = pd.DataFrame(list(string.ascii_lowercase))

In [41]:
for i in range(5):
    letters[f'{i}'] = 1

In [42]:
letters

    0  0  1  2  3  4
0   a  1  1  1  1  1
1   b  1  1  1  1  1
2   c  1  1  1  1  1
3   d  1  1  1  1  1
4   e  1  1  1  1  1
5   f  1  1  1  1  1
6   g  1  1  1  1  1
7   h  1  1  1  1  1
8   i  1  1  1  1  1
9   j  1  1  1  1  1
10  k  1  1  1  1  1
11  l  1  1  1  1  1
12  m  1  1  1  1  1
13  n  1  1  1  1  1
14  o  1  1  1  1  1
15  p  1  1  1  1  1
16  q  1  1  1  1  1
17  r  1  1  1  1  1
18  s  1  1  1  1  1
19  t  1  1  1  1  1
20  u  1  1  1  1  1
21  v  1  1  1  1  1
22  w  1  1  1  1  1
23  x  1  1  1  1  1
24  y  1  1  1  1  1
25  z  1  1  1  1  1

In [43]:
def update(guess: str, response: List[int]):
    """
    Takes in a guess and updates the letters and word_probability 
        guess: 5 letter word
        response: list of responses for the guessed word could be correct
        placement, correct letter, or wrong.
    """
    ...

TypeError: 'type' object is not subscriptable